name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  deploy-docs-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch merge branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r ./dev-requirements/nox.txt

      - name: Build docs
        run: |
          mkdir site
          python -m nox -s generate-docs -- -o ./site

      - name: Archive docs
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ./site
          if-no-files-found: error

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./site/
          preview-branch: docs
