name: Publish documentation

on:
  workflow_call:
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r ./dev-requirements/nox.txt
      - name: Build docs
        id: doc_info
        run: |
          mkdir site
          python -m nox -s generate-docs -- -o ./site -j
          echo "::set-output name=GIT_HASH::$(git rev-parse HEAD)"
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: docs
          FOLDER: ./site
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "${{ steps.doc_info.outputs.GIT_HASH }} docs (${{ github.event.release.tag_name || github.event.ref }})"
          SKIP_EMPTY_COMMITS: true
